version: "3.8"

services:
  kafka_setup:
    build:
      context: .
    container_name: kafka_setup
    networks:
      - pd
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    command: poetry run python /infraestrutura_kafka_pd/kafka_setup/__init__.py

  producer:
    build:
      context: .
    container_name: producer
    networks:
      - pd
    depends_on:
      kafka_setup:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    command: poetry run python /infraestrutura_kafka_pd/producer/__init__.py

  consumer:
    container_name: consumer
    build:
      context: .
    networks:
      - pd
    depends_on:
      kafka_setup:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    command: poetry run python /infraestrutura_kafka_pd/consumer/__init__.py

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - pd
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka1
    networks:
      - pd
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka1-data:/var/lib/kafka/data
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 15s
      timeout: 60s
      retries: 3

  kafka2:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka2
    networks:
      - pd
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9093:9093"
    volumes:
      - kafka2-data:/var/lib/kafka/data
    healthcheck:
      test: nc -z localhost 9093 || exit 1
      interval: 15s
      timeout: 60s
      retries: 3


  kafka3:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka3
    networks:
      - pd
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9094:9094"
    volumes:
      - kafka3-data:/var/lib/kafka/data
    healthcheck:
      test: nc -z localhost 9094 || exit 1
      interval: 15s
      timeout: 60s
      retries: 3

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    networks:
      - pd
    depends_on:
      - kafka1
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka1:9092,kafka2:9093,kafka3:9094"
    ports:
      - "8080:8080"

networks:
  pd:
    name: pd

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka1-data:
  kafka2-data:
  kafka3-data:
