services:

  postgresql:
    image: postgres:13
    container_name: postgresql
    networks:
      - pd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fraudulent_transactions
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - pd
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka1
    networks:
      - pd
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka1-data:/var/lib/kafka/data
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 15s
      timeout: 60s
      retries: 3

  kafka2:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka2
    networks:
      - pd
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9093:9093"
    volumes:
      - kafka2-data:/var/lib/kafka/data

  kafka3:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka3
    networks:
      - pd
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9094:9094"
    volumes:
      - kafka3-data:/var/lib/kafka/data

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    networks:
      - pd
    depends_on:
      - kafka1
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka1:9092,kafka2:9093,kafka3:9094"
    ports:
      - "8080:8080"

  kafka_setup:
    build:
      context: .
    container_name: kafka_setup
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094"
      TOPIC_TRANSACTIONS: "transactions"
      TOPIC_FRAUDULENT_TRANSACTIONS: "fraudulent_transactions"
    networks:
      - pd
    depends_on:
      kafka1:
        condition: service_healthy
    command: poetry run python -m infraestrutura_kafka_pd.kafka_setup.main

  producer:
    build:
      context: .
    container_name: producer
    networks:
      - pd
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094"
      TOPIC_TRANSACTIONS: "transactions"
    depends_on:
      kafka_setup:
        condition: service_completed_successfully
      kafka1:
        condition: service_healthy
    command: poetry run python -m infraestrutura_kafka_pd.producer.main

  consumer:
    build:
      context: .
    container_name: consumer
    networks:
      - pd
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094"
      TOPIC_TRANSACTIONS: "transactions"
      TOPIC_FRAUDULENT_TRANSACTIONS: "fraudulent_transactions"
    depends_on:
      producer:
        condition: service_completed_successfully
      kafka1:
        condition: service_healthy
    command: poetry run python -m infraestrutura_kafka_pd.consumer.main

  consumer_to_db:
    build:
      context: .
    container_name: consumer_to_db
    networks:
      - pd
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094"
      TOPIC_FRAUDULENT_TRANSACTIONS: "fraudulent_transactions"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgresql
      DB_NAME: fraudulent_transactions
    depends_on:
        - consumer
        - postgresql
    command: poetry run python -m infraestrutura_kafka_pd.consumer_to_db.main

networks:
  pd:
    name: pd

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka1-data:
  kafka2-data:
  kafka3-data:
