name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install --no-cache-dir poetry && \
          poetry config virtualenvs.create false && \
          poetry install --no-dev --no-interaction --no-ansi

      - name: Install dependencies
        run: poetry install

      - name: Run Ruff
        run: poetry run ruff check
