name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install poetry==1.7.0

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --only main

      - name: Run Ruff
        run: |
          poetry run ruff check .
